[env:kit_xmc_2go_xmc1100_v1]
platform = infineonxmc
board = kit_xmc_2go_xmc1100_v1
framework = arduino

[env:kit_xmc11_boot_001]
platform = infineonxmc
board = kit_xmc11_boot_001
framework = arduino

[env:kit_xmc13_boot_001]
platform = infineonxmc
board = kit_xmc13_boot_001
framework = arduino

[env:kit_xmc47_relax]
platform = infineonxmc
board = kit_xmc47_relax
framework = arduino
