[env:kit_xmc_2go_xmc1100_v1]
platform = infineonxmc
board = kit_xmc_2go_xmc1100_v1
framework = arduino

[env:kit_xmc11_boot_001]
platform = infineonxmc
board = kit_xmc11_boot_001
framework = arduino

[env:kit_xmc14_2go]
platform = infineonxmc
board = kit_xmc14_2go
framework = arduino

[env:kit_xmc1400_arduino]
platform = infineonxmc
board = kit_xmc1400_arduino
framework = arduino
